In [1]:
import pandas as pd

In [2]:
import os

dataset_folder_path = r"io\courses_new_repaired"  # Use r for raw string to handle backslashes
dataset = [os.path.join(dataset_folder_path, entry.name) for entry in os.scandir(dataset_folder_path) if entry.is_file()]

train_folder_path = r"io\courses_test"  # Use r for raw string to handle backslashes
train = [os.path.join(train_folder_path, entry.name) for entry in os.scandir(train_folder_path) if entry.is_file()]

In [3]:
import json

test = {
    "question": [],
    "query": [],
    "category": []
}

for file in dataset:
    with open(file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    for item in data:
        test["question"].append(item["question"])
        test["query"].append(item["query"])
        test["category"].append(file)

In [4]:
df_test = pd.DataFrame(test)
df_test

,question,query,category
0,What courses have the Digital Library & Distan...,select ?x { ?x <http://example.org/has_researc...,io\courses_new_repaired\complex_1_5_normal.json
1,What course has the evaluation method of Group...,select ?x { ?x <http://example.org/has_evaluat...,io\courses_new_repaired\complex_1_5_normal.json
2,What courses have 'Group Project' and 'Test' a...,select ?x { ?x <http://example.org/has_evaluat...,io\courses_new_repaired\complex_1_5_normal.json
3,What courses have the evaluation method 'Test'...,select ?x { ?x <http://example.org/has_evaluat...,io\courses_new_repaired\complex_1_5_normal.json
4,What courses have Research Methodology and Sci...,select ?x { ?x <http://example.org/has_course_...,io\courses_new_repaired\complex_1_5_normal.json
5,What courses have prerequisite courses that ha...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_new_repaired\complex_2_5_normal.json
6,What courses have study program mandatory cour...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_new_repaired\complex_2_5_normal.json
7,What courses have prerequisites with 3 credits?,select ?x { ?x <http://example.org/has_prerequ...,io\courses_new_repaired\complex_2_5_normal.json
8,What courses have prerequisites with Discrete ...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_new_repaired\complex_2_5_normal.json
9,What courses have prerequisites that have test...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_new_repaired\complex_2_5_normal.json
10,What is the course category of 'Spoken Languag...,select ?x { <http://example.org/spoken_languag...,io\courses_new_repaired\simple_1_10_normal.json
11,What course categories does Bioinformatics bel...,select ?x { <http://example.org/bioinformatics...,io\courses_new_repaired\simple_1_10_normal.json
12,What evaluation methods are associated with 'C...,select ?x { <http://example.org/cryptography_a...,io\courses_new_repaired\simple_1_10_normal.json
13,What courses are prerequisites for Computer Vi...,select ?x { <http://example.org/computer_visio...,io\courses_new_repaired\simple_1_10_normal.json
14,What are the prerequisite courses for Knowledg...,select ?x { <http://example.org/knowledge_repr...,io\courses_new_repaired\simple_1_10_normal.json
15,What is the course category of Discrete Mathem...,select ?x { <http://example.org/discrete_mathe...,io\courses_new_repaired\simple_1_10_normal.json
16,How many credits does 'Introduction to Digital...,select ?x { <http://example.org/introduction_t...,io\courses_new_repaired\simple_1_10_normal.json
17,What evaluation methods are associated with 'C...,select ?x { <http://example.org/cryptography_a...,io\courses_new_repaired\simple_1_10_normal.json
18,What course categories does 'Research Methodol...,select ?x { <http://example.org/research_metho...,io\courses_new_repaired\simple_1_10_normal.json
19,What prerequisite courses does Web Application...,select ?x { <http://example.org/web_applicatio...,io\courses_new_repaired\simple_1_10_normal.json
20,How many evaluation methods are associated wit...,select (count(?x) as ?cnt) { <http://example.o...,io\courses_new_repaired\simple_1_5_count.json
21,How many prerequisite courses does 'Algorithm ...,select (count(?x) as ?cnt) { <http://example.o...,io\courses_new_repaired\simple_1_5_count.json
22,How many courses are prerequisites for Calculu...,select (count(?x) as ?cnt) { <http://example.o...,io\courses_new_repaired\simple_1_5_count.json
23,How many evaluation methods are associated wit...,select (count(?x) as ?cnt) { <http://example.o...,io\courses_new_repaired\simple_1_5_count.json
24,How many evaluation methods of 'Internet of Th...,select (count(?x) as ?cnt) { <http://example.o...,io\courses_new_repaired\simple_1_5_count.json
25,What are the courses that have 'Task' as the e...,select ?x { ?x <http://example.org/has_evaluat...,io\courses_new_repaired\simple_2_10_normal.json
26,What courses have 'Computer network' as a prer...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_new_repaired\simple_2_10_normal.json
27,What are the courses that have 'Test' as their...,select ?x { ?x <http://example.org/has_evaluat...,io\courses_new_repaired\simple_2_10_normal.json
28,What courses have the category 'Study Program ...,select ?x { ?x <http://example.org/has_course_...,io\courses_new_repaired\simple_2_10_normal.json
29,What courses that have 3 credits?,select ?x { ?x <http://example.org/has_credits...,io\courses_new_repaired\simple_2_10_normal.json
30,What course has the course code 'CSCE604222'?,select ?x { ?x <http://example.org/has_course_...,io\courses_new_repaired\simple_2_10_normal.json
31,What courses that have 'Test' as their evaluat...,select ?x { ?x <http://example.org/has_evaluat...,io\courses_new_repaired\simple_2_10_normal.json
32,What courses that have 6 credits?,select ?x { ?x <http://example.org/has_credits...,io\courses_new_repaired\simple_2_10_normal.json
33,What are the courses that have 'Test' as their...,select ?x { ?x <http://example.org/has_evaluat...,io\courses_new_repaired\simple_2_10_normal.json
34,What courses have 'Programming Basics 2' as a ...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_new_repaired\simple_2_10_normal.json
35,How many courses have 'Data Structures and Alg...,select (count(?x) as ?cnt) { ?x <http://exampl...,io\courses_new_repaired\simple_2_5_count.json
36,How many courses have Software engineering as ...,select (count(?x) as ?cnt) { ?x <http://exampl...,io\courses_new_repaired\simple_2_5_count.json
37,How many courses are categorized as 'Faculty M...,select (count(?x) as ?cnt) { ?x <http://exampl...,io\courses_new_repaired\simple_2_5_count.json
38,How many courses with 'Project Assignment' as ...,select (count(?x) as ?cnt) { ?x <http://exampl...,io\courses_new_repaired\simple_2_5_count.json
39,How many courses that have evaluation method '...,select (count(?x) as ?cnt) { ?x <http://exampl...,io\courses_new_repaired\simple_2_5_count.json

In [5]:
df_test = df_test.drop_duplicates(subset="query")
df_test

,question,query,category
0,What courses have the Digital Library & Distan...,select ?x { ?x <http://example.org/has_researc...,io\courses_new_repaired\complex_1_5_normal.json
1,What course has the evaluation method of Group...,select ?x { ?x <http://example.org/has_evaluat...,io\courses_new_repaired\complex_1_5_normal.json
2,What courses have 'Group Project' and 'Test' a...,select ?x { ?x <http://example.org/has_evaluat...,io\courses_new_repaired\complex_1_5_normal.json
3,What courses have the evaluation method 'Test'...,select ?x { ?x <http://example.org/has_evaluat...,io\courses_new_repaired\complex_1_5_normal.json
4,What courses have Research Methodology and Sci...,select ?x { ?x <http://example.org/has_course_...,io\courses_new_repaired\complex_1_5_normal.json
5,What courses have prerequisite courses that ha...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_new_repaired\complex_2_5_normal.json
6,What courses have study program mandatory cour...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_new_repaired\complex_2_5_normal.json
7,What courses have prerequisites with 3 credits?,select ?x { ?x <http://example.org/has_prerequ...,io\courses_new_repaired\complex_2_5_normal.json
8,What courses have prerequisites with Discrete ...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_new_repaired\complex_2_5_normal.json
9,What courses have prerequisites that have test...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_new_repaired\complex_2_5_normal.json
10,What is the course category of 'Spoken Languag...,select ?x { <http://example.org/spoken_languag...,io\courses_new_repaired\simple_1_10_normal.json
11,What course categories does Bioinformatics bel...,select ?x { <http://example.org/bioinformatics...,io\courses_new_repaired\simple_1_10_normal.json
12,What evaluation methods are associated with 'C...,select ?x { <http://example.org/cryptography_a...,io\courses_new_repaired\simple_1_10_normal.json
13,What courses are prerequisites for Computer Vi...,select ?x { <http://example.org/computer_visio...,io\courses_new_repaired\simple_1_10_normal.json
14,What are the prerequisite courses for Knowledg...,select ?x { <http://example.org/knowledge_repr...,io\courses_new_repaired\simple_1_10_normal.json
15,What is the course category of Discrete Mathem...,select ?x { <http://example.org/discrete_mathe...,io\courses_new_repaired\simple_1_10_normal.json
16,How many credits does 'Introduction to Digital...,select ?x { <http://example.org/introduction_t...,io\courses_new_repaired\simple_1_10_normal.json
18,What course categories does 'Research Methodol...,select ?x { <http://example.org/research_metho...,io\courses_new_repaired\simple_1_10_normal.json
19,What prerequisite courses does Web Application...,select ?x { <http://example.org/web_applicatio...,io\courses_new_repaired\simple_1_10_normal.json
20,How many evaluation methods are associated wit...,select (count(?x) as ?cnt) { <http://example.o...,io\courses_new_repaired\simple_1_5_count.json
21,How many prerequisite courses does 'Algorithm ...,select (count(?x) as ?cnt) { <http://example.o...,io\courses_new_repaired\simple_1_5_count.json
22,How many courses are prerequisites for Calculu...,select (count(?x) as ?cnt) { <http://example.o...,io\courses_new_repaired\simple_1_5_count.json
23,How many evaluation methods are associated wit...,select (count(?x) as ?cnt) { <http://example.o...,io\courses_new_repaired\simple_1_5_count.json
24,How many evaluation methods of 'Internet of Th...,select (count(?x) as ?cnt) { <http://example.o...,io\courses_new_repaired\simple_1_5_count.json
25,What are the courses that have 'Task' as the e...,select ?x { ?x <http://example.org/has_evaluat...,io\courses_new_repaired\simple_2_10_normal.json
26,What courses have 'Computer network' as a prer...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_new_repaired\simple_2_10_normal.json
27,What are the courses that have 'Test' as their...,select ?x { ?x <http://example.org/has_evaluat...,io\courses_new_repaired\simple_2_10_normal.json
28,What courses have the category 'Study Program ...,select ?x { ?x <http://example.org/has_course_...,io\courses_new_repaired\simple_2_10_normal.json
29,What courses that have 3 credits?,select ?x { ?x <http://example.org/has_credits...,io\courses_new_repaired\simple_2_10_normal.json
30,What course has the course code 'CSCE604222'?,select ?x { ?x <http://example.org/has_course_...,io\courses_new_repaired\simple_2_10_normal.json
32,What courses that have 6 credits?,select ?x { ?x <http://example.org/has_credits...,io\courses_new_repaired\simple_2_10_normal.json
34,What courses have 'Programming Basics 2' as a ...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_new_repaired\simple_2_10_normal.json
35,How many courses have 'Data Structures and Alg...,select (count(?x) as ?cnt) { ?x <http://exampl...,io\courses_new_repaired\simple_2_5_count.json
36,How many courses have Software engineering as ...,select (count(?x) as ?cnt) { ?x <http://exampl...,io\courses_new_repaired\simple_2_5_count.json
37,How many courses are categorized as 'Faculty M...,select (count(?x) as ?cnt) { ?x <http://exampl...,io\courses_new_repaired\simple_2_5_count.json
38,How many courses with 'Project Assignment' as ...,select (count(?x) as ?cnt) { ?x <http://exampl...,io\courses_new_repaired\simple_2_5_count.json
39,How many courses that have evaluation method '...,select (count(?x) as ?cnt) { ?x <http://exampl...,io\courses_new_repaired\simple_2_5_count.json

In [6]:
import re

def replace_prefix(query):
    query = re.sub(r'<http://example.org/', 'ns1:', query)
    query = re.sub(r'>', '', query)
    return query

df_test['query'] = df_test['query'].apply(replace_prefix)
df_test

C:\Users\jayce\AppData\Local\Temp\ipykernel_25368\3406898892.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['query'] = df_test['query'].apply(replace_prefix)

,question,query,category
0,What courses have the Digital Library & Distan...,select ?x { ?x ns1:has_research_group ns1:digi...,io\courses_new_repaired\complex_1_5_normal.json
1,What course has the evaluation method of Group...,select ?x { ?x ns1:has_evaluation_method ns1:g...,io\courses_new_repaired\complex_1_5_normal.json
2,What courses have 'Group Project' and 'Test' a...,select ?x { ?x ns1:has_evaluation_method ns1:g...,io\courses_new_repaired\complex_1_5_normal.json
3,What courses have the evaluation method 'Test'...,select ?x { ?x ns1:has_evaluation_method ns1:t...,io\courses_new_repaired\complex_1_5_normal.json
4,What courses have Research Methodology and Sci...,select ?x { ?x ns1:has_course_category ns1:fac...,io\courses_new_repaired\complex_1_5_normal.json
5,What courses have prerequisite courses that ha...,select ?x { ?x ns1:has_prerequisite_course ?y ...,io\courses_new_repaired\complex_2_5_normal.json
6,What courses have study program mandatory cour...,select ?x { ?x ns1:has_prerequisite_course ?y ...,io\courses_new_repaired\complex_2_5_normal.json
7,What courses have prerequisites with 3 credits?,select ?x { ?x ns1:has_prerequisite_course ?y ...,io\courses_new_repaired\complex_2_5_normal.json
8,What courses have prerequisites with Discrete ...,select ?x { ?x ns1:has_prerequisite_course ?y ...,io\courses_new_repaired\complex_2_5_normal.json
9,What courses have prerequisites that have test...,select ?x { ?x ns1:has_prerequisite_course ?y ...,io\courses_new_repaired\complex_2_5_normal.json
10,What is the course category of 'Spoken Languag...,select ?x { ns1:spoken_language_processing ns1...,io\courses_new_repaired\simple_1_10_normal.json
11,What course categories does Bioinformatics bel...,select ?x { ns1:bioinformatics ns1:has_course_...,io\courses_new_repaired\simple_1_10_normal.json
12,What evaluation methods are associated with 'C...,select ?x { ns1:cryptography_and_information_s...,io\courses_new_repaired\simple_1_10_normal.json
13,What courses are prerequisites for Computer Vi...,select ?x { ns1:computer_vision ns1:has_prereq...,io\courses_new_repaired\simple_1_10_normal.json
14,What are the prerequisite courses for Knowledg...,select ?x { ns1:knowledge_representation_and_r...,io\courses_new_repaired\simple_1_10_normal.json
15,What is the course category of Discrete Mathem...,select ?x { ns1:discrete_mathematics_2 ns1:has...,io\courses_new_repaired\simple_1_10_normal.json
16,How many credits does 'Introduction to Digital...,select ?x { ns1:introduction_to_digital_system...,io\courses_new_repaired\simple_1_10_normal.json
18,What course categories does 'Research Methodol...,select ?x { ns1:research_methodology_and_scien...,io\courses_new_repaired\simple_1_10_normal.json
19,What prerequisite courses does Web Application...,select ?x { ns1:web_application_architecture n...,io\courses_new_repaired\simple_1_10_normal.json
20,How many evaluation methods are associated wit...,select (count(?x) as ?cnt) { ns1:bioinformatic...,io\courses_new_repaired\simple_1_5_count.json
21,How many prerequisite courses does 'Algorithm ...,select (count(?x) as ?cnt) { ns1:algorithm_des...,io\courses_new_repaired\simple_1_5_count.json
22,How many courses are prerequisites for Calculu...,select (count(?x) as ?cnt) { ns1:calculus_2 ns...,io\courses_new_repaired\simple_1_5_count.json
23,How many evaluation methods are associated wit...,select (count(?x) as ?cnt) { ns1:natural_langu...,io\courses_new_repaired\simple_1_5_count.json
24,How many evaluation methods of 'Internet of Th...,select (count(?x) as ?cnt) { ns1:internet_of_t...,io\courses_new_repaired\simple_1_5_count.json
25,What are the courses that have 'Task' as the e...,select ?x { ?x ns1:has_evaluation_method ns1:t...,io\courses_new_repaired\simple_2_10_normal.json
26,What courses have 'Computer network' as a prer...,select ?x { ?x ns1:has_prerequisite_course ns1...,io\courses_new_repaired\simple_2_10_normal.json
27,What are the courses that have 'Test' as their...,select ?x { ?x ns1:has_evaluation_method ns1:t...,io\courses_new_repaired\simple_2_10_normal.json
28,What courses have the category 'Study Program ...,select ?x { ?x ns1:has_course_category ns1:stu...,io\courses_new_repaired\simple_2_10_normal.json
29,What courses that have 3 credits?,select ?x { ?x ns1:has_credits '3'^^xsd:intege...,io\courses_new_repaired\simple_2_10_normal.json
30,What course has the course code 'CSCE604222'?,select ?x { ?x ns1:has_course_code 'CSCE604222...,io\courses_new_repaired\simple_2_10_normal.json
32,What courses that have 6 credits?,select ?x { ?x ns1:has_credits '6'^^xsd:intege...,io\courses_new_repaired\simple_2_10_normal.json
34,What courses have 'Programming Basics 2' as a ...,select ?x { ?x ns1:has_prerequisite_course ns1...,io\courses_new_repaired\simple_2_10_normal.json
35,How many courses have 'Data Structures and Alg...,select (count(?x) as ?cnt) { ?x ns1:has_prereq...,io\courses_new_repaired\simple_2_5_count.json
36,How many courses have Software engineering as ...,select (count(?x) as ?cnt) { ?x ns1:has_prereq...,io\courses_new_repaired\simple_2_5_count.json
37,How many courses are categorized as 'Faculty M...,select (count(?x) as ?cnt) { ?x ns1:has_course...,io\courses_new_repaired\simple_2_5_count.json
38,How many courses with 'Project Assignment' as ...,select (count(?x) as ?cnt) { ?x ns1:has_evalua...,io\courses_new_repaired\simple_2_5_count.json
39,How many courses that have evaluation method '...,select (count(?x) as ?cnt) { ?x ns1:has_evalua...,io\courses_new_repaired\simple_2_5_count.json

In [10]:
df_test.to_json(r"io/final_dataset/test.json")

In [11]:
import json

train_set = {
    "question": [],
    "query": [],
    "category": []
}

for file in train:
    with open(file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    for item in data:
        train_set["question"].append(item["question"])
        train_set["query"].append(item["query"])
        train_set["category"].append(file)

In [12]:
df_train = pd.DataFrame(train_set)
df_train

,question,query,category
0,What faculty mandatory course that have 'Test'...,select ?x { ?x <http://example.org/has_course_...,io\courses_test\complex_1_1_normal.json
1,What courses have prerequisites that falls und...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_test\complex_2_1_normal.json
2,How many research groups does the 'Computer Sc...,select (count(?x) as ?cnt) { <http://example.o...,io\courses_test\simple_1_1_count.json
3,What evaluation methods does Software engineer...,select ?x { <http://example.org/software_engin...,io\courses_test\simple_1_2_normal.json
4,What evaluation methods does Deep Learning have?,select ?x { <http://example.org/deep_learning>...,io\courses_test\simple_1_2_normal.json
5,How many courses have 'Programming projects an...,select (count(?x) as ?cnt) { ?x <http://exampl...,io\courses_test\simple_2_1_count.json
6,What courses are included in the research grou...,select ?x { ?x <http://example.org/has_researc...,io\courses_test\simple_2_2_normal.json
7,What courses have 'Introduction to Artificial ...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_test\simple_2_2_normal.json

In [13]:
df_train = df_train.drop_duplicates(subset="query")
df_train

,question,query,category
0,What faculty mandatory course that have 'Test'...,select ?x { ?x <http://example.org/has_course_...,io\courses_test\complex_1_1_normal.json
1,What courses have prerequisites that falls und...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_test\complex_2_1_normal.json
2,How many research groups does the 'Computer Sc...,select (count(?x) as ?cnt) { <http://example.o...,io\courses_test\simple_1_1_count.json
3,What evaluation methods does Software engineer...,select ?x { <http://example.org/software_engin...,io\courses_test\simple_1_2_normal.json
4,What evaluation methods does Deep Learning have?,select ?x { <http://example.org/deep_learning>...,io\courses_test\simple_1_2_normal.json
5,How many courses have 'Programming projects an...,select (count(?x) as ?cnt) { ?x <http://exampl...,io\courses_test\simple_2_1_count.json
6,What courses are included in the research grou...,select ?x { ?x <http://example.org/has_researc...,io\courses_test\simple_2_2_normal.json
7,What courses have 'Introduction to Artificial ...,select ?x { ?x <http://example.org/has_prerequ...,io\courses_test\simple_2_2_normal.json

In [14]:
df_train['query'] = df_train['query'].apply(replace_prefix)
df_train

,question,query,category
0,What faculty mandatory course that have 'Test'...,select ?x { ?x ns1:has_course_category ns1:fac...,io\courses_test\complex_1_1_normal.json
1,What courses have prerequisites that falls und...,select ?x { ?x ns1:has_prerequisite_course ?y ...,io\courses_test\complex_2_1_normal.json
2,How many research groups does the 'Computer Sc...,select (count(?x) as ?cnt) { ns1:computer_scie...,io\courses_test\simple_1_1_count.json
3,What evaluation methods does Software engineer...,select ?x { ns1:software_engineering ns1:has_e...,io\courses_test\simple_1_2_normal.json
4,What evaluation methods does Deep Learning have?,select ?x { ns1:deep_learning ns1:has_evaluati...,io\courses_test\simple_1_2_normal.json
5,How many courses have 'Programming projects an...,select (count(?x) as ?cnt) { ?x ns1:has_evalua...,io\courses_test\simple_2_1_count.json
6,What courses are included in the research grou...,select ?x { ?x ns1:has_research_group ns1:reli...,io\courses_test\simple_2_2_normal.json
7,What courses have 'Introduction to Artificial ...,select ?x { ?x ns1:has_prerequisite_course ns1...,io\courses_test\simple_2_2_normal.json

In [15]:
df_train.to_json(r"io/final_dataset/train.json")